name: PUT-labs-instructions-CI-demonstration

# Run on schedule, cron syntax, everyday at 9:45 and on push
on:
  push:
  schedule:
    - cron:  '45 9 * * *'

env:
  WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY1 }}

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Sphinx
        run: |
          sudo apt-get install python3-sphinx
      - name: Build HTML artifacts
        run: |
          sphinx-build -E -W -b html source build/html
      - uses: actions/upload-artifact@v3
        with:
          name: lab_html
          path: build/html

  test-external-links:
    needs: build-artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Sphinx # Sphinx installation is duplicated...
        run: |
          sudo apt-get install python3-sphinx
      - name: Test external links with linkcheck builder
        run: |
          sphinx-build -E -W -b linkcheck source build/linkcheck
      - uses: actions/upload-artifact@v3
        with:
          name: linkcheck_out
          path: build/linkcheck

  # This has to be prepped manually, but it represents general case that cannot
  # automated in Sphinx only, but other tools are necessary
  test-api-access:
    needs: build-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Echo secret test
        run: |
          echo "${WEATHER_API_KEY}"
      - name: Test curl string
        run: |
          echo "https://api.openweathermap.org/data/2.5/weather?lat=44.34&lon=10.99&appid=${WEATHER_API_KEY}"
      - name: Test Weather API access
        run: |
          curl "https://api.openweathermap.org/data/2.5/weather?lat=44.34&lon=10.99&appid=${WEATHER_API_KEY}"



