name: PUT-labs-instructions-CI-demonstration

# Run on schedule, cron syntax, everyday at 9:45 and on push
on:
  push:
  schedule:
    - cron:  '45 9 * * *'

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Sphinx
        run: |
          sudo apt-get install python3-sphinx
      - name: Build HTML artifacts
        run: |
          sphinx-build -E -W -b html source build/html
      - uses: actions/upload-artifact@v3
        with:
          name: lab_html
          path: build/html

  test-external-links:
    needs: build-artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Sphinx # Sphinx installation is duplicated...
        run: |
          sudo apt-get install python3-sphinx
      - name: Test external links with linkcheck builder
        run: |
          sphinx-build -E -W -b linkcheck source build/linkcheck
      - uses: actions/upload-artifact@v3
        with:
          name: linkcheck_out
          path: build/linkcheck


