name: PUT-labs-instructions-CI-demonstration

# Run on schedule, cron syntax, everyday at 9:45
on:
  push:
  schedule:
    - cron:  '45 9 * * *'

jobs:
  tests: # We could also specify range of Python versions and modules versions to run tests against
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Sphinx
        run: |
          sudo apt-get install python3-sphinx
      - name: Stub
        run: |
          ls

  build-artifacts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Sphinx
        run: |
          sudo apt-get install python3-sphinx
      - name: Build HTML artifacts
        run: |
          sphinx-build -E -W -b html source build/html
      - uses: actions/upload-artifact@v3
        with:
          name: output_doc
          path: build/html

