name: PUT-labs-instructions-CI-demonstration

# Run on schedule, cron syntax, everyday at 9:45 and on push
on:
  push:
  schedule:
    - cron:  '45 9 * * *'

env:
  HTML_OUT: build/html
  LINKCHECK_OUT: build/linkcheck
  DOCTEST_OUT: build/doctest

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Path test
        run: echo "$HTML_OUT"
      - name: Second path test
        run: echo "$LINKCHECK_OUT"
      - uses: actions/checkout@v3
      - name: Install Sphinx
        run: |
          sudo apt-get install python3-sphinx
      - name: Build HTML artifacts
        run: |
          sphinx-build -E -W -b html source $HTML_OUT
      - uses: actions/upload-artifact@v3
        with:
          name: lab_html
          path: $HTML_OUT

  test-external-links:
    needs: build-artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Sphinx # Sphinx installation is duplicated...
        run: |
          sudo apt-get install python3-sphinx
      - name: Test external links with linkcheck builder
        run: |
          sphinx-build -E -W -b linkcheck source $LINKCHECK_OUT
      - uses: actions/upload-artifact@v3
        with:
          name: linkcheck_out
          path: $LINKCHECK_OUT


